# Generated by Django 6.1 on 2026-08-31 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='uaername',
            new_name='username',
        ),
    ]
